### ISSUE TITLE
JSON output type produced decimal number instead of integers

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.PostgreSQL#7]
1. Test e.g. with the query `SELECT date_part('month', somedate)`.
2. Set output type as JSON
3. In result you will have the month number as e.g. `12.0` (December) instead of just `12`.

**Comment by RikuVirtanen** [comment]
@jefim is this in correct Task? There's no selection for output type in the Task.

**Comment by jefim** [comment]
Yeah, this is wrong place for this bug report, it should be on community side.

**Comment by jefim** [comment]
(moved to https://github.com/CommunityHiQ/Frends.Community.Postgre/issues/18)
